# The comments aren't made by me (Ceiridge), but by some nice author that made the default github actions workflow template :)
name: Build And Release

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build the project with MSBuild
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" -t:restore
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ChromeDevExtWarningPatcher.sln -p:Configuration=Release

    # Test: Check if the file is there
    - name: List release folders
      shell: cmd
      run: |
        cd ChromeDevExtWarningPatcher\bin\Release
        dir
