name: Build And Release

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup NuGet for use with actions
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: '5.x'

    - name: Restore the Nuget packages
      shell: cmd
      run: |
        nuget restore ChromeDevExtWarningPatcher.sln

    - name: Write code sign file
      id: write_file
      if: ${{ github.event_name == 'push' && endsWith(github.ref, '/master') }} # never write code sign file on pull requests
      uses: Ceiridge/base64-to-file@master
      with:
        fileName: 'codesign.pfx'
        encodedString: ${{ secrets.CODE_SIGN_PFX }}

    - name: Copy code sign file
      if: ${{ github.event_name == 'push' && endsWith(github.ref, '/master') }} # never write code sign file on pull requests
      shell: cmd
      env:
        PFXLOC: ${{ steps.write_file.outputs.filePath }}
      run: |
        copy /Y %PFXLOC% ./codesign.pfx
        dir

    - name: Add signtool to PATH
      shell: cmd
      run: |
        echo "::add-path::C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\"

    - name: Build with MSBuild
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ChromeDevExtWarningPatcher.sln -p:Configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: built-gui-binaries
        path: ChromeDevExtWarningPatcher/bin/Release/

    - uses: actions/upload-artifact@v2
      with:
        name: built-native-binaries
        path: x64/

    - name: Zip the builds
      shell: powershell
      run: |
        cd ChromeDevExtWarningPatcher\bin\Release;
        Compress-Archive -DestinationPath ChromeDevExtWarningPatcher.zip -Path ChromeDevExtWarningPatcher.exe,CommandLine.dll,Microsoft.Win32.TaskScheduler.dll,DotNetZip.dll;
        dir;

    - uses: "Ceiridge/action-automatic-releases@master" # actually made by marvinpinto
      if: ${{ github.event_name == 'push' && endsWith(github.ref, '/master') }} # don't release on pull requests
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: "Prerelease Build"
        files: |
          ChromeDevExtWarningPatcher/bin/Release/ChromeDevExtWarningPatcher.zip
